server:
  port: 8083

spring:
  application:
    name: game-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/gamedb
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

redis:
    host: redis
    port: 6379

jwt:
  secret: hKfYbV1L1LwzFX2Yw8hEHyTj3E4xjV5SyJ6eR3Jg+oE=

#kafka:
#  bootstrap-servers: localhost:9092
#  consumer:
#    group-id: game-service-group
#    auto-offset-reset: earliest