server:
  port: 8080

spring:
  application:
    name: game-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gamedb
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: game-service-group
    auto-offset-reset: earliest